package.json, packages/styles/package.json, packages/styles/src/theme.ts, yarn.lock
=> Add ability to extend theme

packages/components/src/Button/Button.style.ts, packages/components/src/Button/Button.tsx, packages/components/src/Metric/Metric.style.ts, packages/components/src/Metric/Metric.tsx
Style textPrimary variant of Button, rename titleSize Metric prop to size
=> feat: extend Button and Metric components

packages/components/src/TabsSection/TabsSection.style.ts, packages/components/src/TabsSection/TabsSection.tsx, packages/components/src/inputs/SelectInput/SelectInput.style.ts, packages/components/src/inputs/SelectInput/SelectInput.tsx
Fix tabs and select widths.
Fix select positioning on low resolutions.
=> Fix tabs, selectInput widths, fix select input positioning

packages/components/src/TabsSection/TabsSection.style.ts, packages/components/src/TabsSection/TabsSection.tsx
Reverts akropolisio/akropolis-web#52
=> Revert "feat(tabssection): add optional disabling margin"

packages/styles/src/theme.ts
https://app.asana.com/0/1181150566095458/1199232958858300/f
=> refactor: add global styles override for tooltip

packages/primitives/src/bnHexWei/utils/getSignificantValue.ts, packages/primitives/src/entities/amount/Amount.ts
Indirectly solves these issues:
https://app.asana.com/0/1198976410300181/1199099610149734/f
https://app.asana.com/0/0/1199099066398407/f
=> feat: add toSignificantValue() in Amount, refactor getSignificantValue()

packages/components/src/Button/Button.style.ts
https://akro.atlassian.net/browse/DD-1351?atlOrigin=eyJpIjoiYTgzNGNhNTZmZjUzNDc2ZDk0OTAyZWIzMzA3MGNkODQiLCJwIjoiaiJ9
=> fix: override hover styles for disabled button

packages/components/src/Label/Label.tsx
https://akro.atlassian.net/browse/DD-1405?focusedCommentId=10326
=> style(label): change tooltip font size

packages/components/src/inputs/AmountInput/AmountInput.tsx
https://akro.atlassian.net/browse/DD-1296?focusedCommentId=10337
=> feat(amountinput): dd-1296 add allowedMax prop

packages/components/src/inputs/LiquidityAmountInput.tsx
https://akro.atlassian.net/browse/DD-1595
=> feat: add currency icon to liquidity amount DD-1595

packages/components/src/icons/Arrow.tsx, packages/components/src/inputs/AmountInput/AmountInput.tsx, packages/components/src/inputs/SelectInput/SelectInput.style.ts, packages/components/src/inputs/SelectInput/SelectInput.tsx, packages/components/src/inputs/index.ts
https://akro.atlassian.net/browse/DD-1473?atlOrigin=eyJpIjoiOWI0MThjNTE2MmFiNDA1ZWI2Yjg0YzcwMmM5MDRjMDAiLCJwIjoiaiJ9
=> fix: disabled SelectInput props, move single option logic to AmountInput

packages/components/src/TokenName/TokenName.tsx, packages/primitives/src/entities/AllCoinsToken.ts
https://akro.atlassian.net/browse/DD-1682?atlOrigin=eyJpIjoiM2NjY2NlNmI3MDQ0NGMzZTlkOTFmNmUwNzRkOGI4NjEiLCJwIjoiaiJ9
=> feat: support AllCoinsToken in TokenName

packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-1804
=> feat(theme): DD-1804 Add global transtition for all elements

packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2064?atlOrigin=eyJpIjoiODE3YmQ2ZTUyOTI1NGEyM2FiN2FjODE5N2YzZDExYzUiLCJwIjoiaiJ9
=> fix: [DD-2064] fix tab text opacity

packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2103
=> feat: [DD-2103] Override skeleton background

packages/components/src/Button/Button.tsx, packages/components/src/inputs/SelectInput/SelectInput.style.ts, packages/components/src/inputs/SelectInput/SelectInput.tsx, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2173?focusedCommentId=12256
=> feat(selectinput): [DD-2173] Add select without outline

packages/components/src/inputs/SelectInput/SelectInput.style.ts, packages/components/src/inputs/SelectInput/SelectInput.tsx
https://akro.atlassian.net/browse/DD-2231?focusedCommentId=12431
=> feat(selectinput): [DD-2247] Show checkmarks in multiselect

packages/components/src/TokenIcon/TokenIcon.tsx
https://akro.atlassian.net/browse/DD-2353
=> feat: [DD-2353] Add BTCB token icon

packages/components/src/Accordion/Accordion.tsx, packages/components/src/index.ts, packages/components/src/temp23/utils/react/attachStaticFields.ts, packages/components/src/temp23/utils/react/index.ts, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2445?atlOrigin=eyJpIjoiZjkyYzM5MDE4NTk0NGRiNjg2YWM2MDdkMTNhMzU3MDEiLCJwIjoiaiJ9
=> feat: [DD-2445] Add Accordion component

packages/components/src/icons/tokens/DelphiPoolIcon.tsx, packages/styles/src/colors.ts, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2497
=> feat: [DD-2497] Add secondary input color, remove delphi cat background

packages/components/src/inputs/CheckboxInput/CheckboxInput.tsx
https://akro.atlassian.net/browse/DD-2513
=> fix: [DD-2513] Extend CheckboxInput props

packages/components/src/TokenIcon/TokenIcon.tsx, packages/components/src/icons/tokens/CrvIBIcon.tsx, packages/components/src/icons/tokens/index.ts
https://akro.atlassian.net/browse/DD-2453
=> feat: [DD-2453] Add crvIB icon, fix AddressIcon position in TokenIcon"

packages/components/src/inputs/DecimalsInput.tsx
https://akro.atlassian.net/browse/DD-2611
=> fix: [DD-2611] Change input Max button case

packages/components/src/inputs/SelectInput/SelectInput.style.ts, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2613
=> feat: [DD-2613] Change inputs bg, disabled tabs bg

packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2625
Related PR: https://github.com/akropolisio/akropolis-frontend/pull/708
=> feat: [DD-2625] Change disabled input placeholder

packages/components/src/inputs/RadioButton/RadioButton.style.ts, packages/components/src/inputs/RadioButton/RadioButton.tsx
https://akro.atlassian.net/browse/DD-2624
related PR: https://github.com/akropolisio/akropolis-frontend/pull/713
=> feat: [DD-2624] Add secondary color for radio button

packages/components/src/icons/currencies/USDIcon.tsx, packages/components/src/icons/currencies/index.ts, packages/components/src/inputs/SelectInput/SelectInput.style.ts, packages/components/src/inputs/SelectInput/SelectInput.tsx, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2646
=> DD-2646 Add filled variant of select

packages/components/src/ShortAddress/ShortAddress.tsx
https://akro.atlassian.net/browse/DD-2765
=> fix: [DD-2765] Show ShortAddress tooltip on mobile

packages/components/src/ShortAddress/ShortAddress.style.ts, packages/components/src/ShortAddress/ShortAddress.tsx
https://akro.atlassian.net/browse/DD-2765
=> fix: [DD-2765] Fix ShortAddress ripple and tooltip styles

packages/components/src/inputs/AmountInput/AmountInput.style.ts, packages/components/src/inputs/DatepickerInput/DatepickerInput.style.ts, packages/components/src/inputs/SelectInput/SelectInput.style.ts, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2791
=> feat: [DD-2791] Change selects and inputs styles

packages/primitives/src/entities/Token.ts, packages/primitives/src/entities/index.ts, packages/primitives/src/entities/types.ts
https://akro.atlassian.net/browse/DD-2802
=> refactor: [DD-2802] Enable Network type overrides

packages/components/src/inputs/SelectInput/SelectInput.style.ts
https://github.com/akropolisio/akropolis-frontend/pull/808#issuecomment-931144976
https://akro.atlassian.net/browse/DD-2791
=> fix: [DD-2791] Fix select border-radius

packages/components/src/Skeleton/Skeleton.tsx, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-2817
=> feat: [DD-2817] Add border radius prop to skeleton

packages/components/src/SelectInput/SelectInput.tsx
Related PR: https://github.com/akropolisio/akropolis-frontend/pull/942
=> refactor: [DD-3000] Add disabled prop for select option

packages/components/package.json, packages/components/src/DatepickerInput/DatepickerInput.tsx, yarn.lock
https://akro.atlassian.net/browse/DD-3010
Related PR: https://github.com/akropolisio/akropolis-frontend/pull/946
=> DD-3010 Add locales for datepicker

packages/styles/src/colors.ts, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-3065
=> feat: [DD-3065] Add gradients for light theme

packages/components/src/SelectInput/SelectInput.style.ts, packages/styles/src/theme.ts
https://akro.atlassian.net/browse/DD-3066
https://akro.atlassian.net/browse/DD-3074
Related PR: https://github.com/akropolisio/akropolis-frontend/pull/969
=> DD-3066 Change light theme colors

packages/components/src/Button/Button.style.ts, packages/components/src/icons/CheckmarkIcon.tsx, packages/styles/src/colors.ts, packages/styles/src/theme.ts
Related PR: https://github.com/akropolisio/akropolis-frontend/pull/976
=> feat: [DD-3073] Add light mode for disabled  button

packages/components/src/SelectInput/SelectInput.style.ts, packages/components/src/ShortAddress/ShortAddress.style.ts, packages/styles/src/colors.ts
Related PR: https://github.com/akropolisio/akropolis-frontend/pull/978
=> DD-3067 Update select input and short address
